version: '1.0.0'

services:
  app:
    container_name: inquiry_backend
    image: hicsail/fhs-online-inquiry-system-backend:main
    restart:  always
    env_file:
      - ../stack.env
    depends_on:
      - db
    ports:
      - 3011:3000
  db:
    image:  postgres:14.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart:  always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 10
      start_period: 30s
    volumes:
        - ./fhs_2.sql:/docker-entrypoint-initdb.d/fhs_2.sql

